# Default configuration for MCP OData bridge
# All settings are read from this file; environment variables are ignored.
mode: http
# port used for HTTP server
port: 8000
# dir: ./metadata
# db_file: shared.sqlite
# base_url: https://sapes5.sapdevcenter.com/sap/opu/odata/sap
# odata_user: username
# odata_pass: password
